language: scala
script:
  - sbt compile
  - sbt test
  - sbt docker:publishLocal
  - sbt docker:publish
scala:
  - 2.11.8
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
  