apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: akka-test-deployment
  labels:
    gitRev: "b5b13fa"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: akka-test
      labels:
        app: akka-test
    spec:
      imagePullSecrets:
        - name: cpy-docker-test-registry
      containers:
      - name: akka-test
        image: elmarweber/kamon-akka-http-tracing-examples:1.0.0-e4ec545
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        args: [
          "-Djava.security.egd=file:/dev/./urandom",
          "-Xmx1g",
          "-Dkamon.jaeger.host=jaeger-agent.jaeger.svc.cluster.local",
        ]
