apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kate-gateway-deployment
  labels:
    gitRev: "b5b13fa"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kate-gateway
      labels:
        app: kate-gateway
    spec:
      imagePullSecrets:
        - name: cpy-docker-test-registry
      containers:
      - name: kate-gateway
        image: elmarweber/kamon-akka-http-tracing-kate-gateway:1.0.0-b5efbaa
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        args: [
          "-Djava.security.egd=file:/dev/./urandom",
          "-Xmx1g",
          "-Dservice.interface.port=9090",
          "-Dservice.auth.endpoint=http://kate-auth-service",
          "-Dservice.cool-stuff.endpoint=http://kate-cool-stuff-service",
          "-Dkamon.jaeger.host=jaeger-agent.jaeger.svc.cluster.local",
        ]
