apiVersion: v1
kind: Service
metadata:
  name: kate-gateway-service
spec:
  ports:
  - name: kate-gateway-service-80
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: kate-gateway
  type: LoadBalancer
