apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kate-analytics-pipeline-deployment
  labels:
    gitRev: "af01608"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kate-analytics-pipeline
      labels:
        app: kate-analytics-pipeline
    spec:
      imagePullSecrets:
        - name: cpy-docker-test-registry
      containers:
      - name: kate-analytics-pipeline
        image: elmarweber/kamon-akka-example-analytics-pipeline:1.0.0-af01608
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        - name: KUBERNETES_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args: [
          "-Djava.security.egd=file:/dev/./urandom",
          "-Xmx1g",
          "-Dservice.http.port=9090",
          "-Dkamon.jaeger.host=jaeger-agent.jaeger.svc.cluster.local",
        ]
