apiVersion: v1
kind: Service
metadata:
  name: kate-cool-stuff-service
spec:
  ports:
  - name: kate-cool-stuff-service-80
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: kate-cool-stuff
  type: ClusterIP
