apiVersion: v1
kind: Service
metadata:
  name: kate-auth-service
spec:
  ports:
  - name: kate-auth-service-80
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: kate-auth
  type: ClusterIP
