apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kate-analytics-pipeline-deployment
  labels:
    gitRev: "b5b13fa"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kate-analytics-pipeline
      labels:
        app: kate-analytics-pipeline
    spec:
      imagePullSecrets:
        - name: cpy-docker-test-registry
      containers:
      - name: kate-analytics-pipeline
        image: elmarweber/kamon-akka-example-analytics-pipeline:1.0.0-b5efbaa
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        args: [
          "-Djava.security.egd=file:/dev/./urandom",
          "-Xmx1g",
          "-Dservice.http.port=9090",
          "-Dkamon.jaeger.host=jaeger-agent.jaeger.svc.cluster.local",
        ]
